name: endra_canasta
description: Endra Canasta interactive prototype
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0\n  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/file_00000000d86c81f6abb580399b68e086.png"
  adaptive_icon_background: "#0C0910"
  adaptive_icon_foreground: "assets/file_00000000d86c81f6abb580399b68e086.png"
  remove_alpha_ios: true
